version: '3.5'

services:
  db:
    image: 'library/postgres:9.5'
    environment:
      POSTGRES_PASSWORD: musicloud
      POSTGRES_USER: musicloud
    volumes:
      - postgres:/var/lib/postgresql/data
  php-fpm:
    user: "$UID"
    build:
      context: .
      dockerfile: docker/php-fpm/Dockerfile
    depends_on:
      - db
    environment:
      DB_HOSTNAME: db
      DB_DATABASE: musicloud
      DB_USERNAME: musicloud
      DB_PASSWORD: musicloud
    volumes:
      - media:/volume/media
      - temp:/volume/temp
  nginx:
    build:
      context: .
      dockerfile: docker/nginx/Dockerfile
    ports:
    - 3030:8080
    depends_on:
      - php-fpm
  migration:
    build:
      context: .
      dockerfile: docker/migration/Dockerfile
    restart: on-failure
    environment:
      POSTGRES_HOST: db
      POSTGRES_DB: musicloud
      POSTGRES_USER: musicloud
      POSTGRES_PASSWORD: musicloud
    depends_on:
      - db
volumes:
  media:
    driver: local
  temp:
    driver: local
  postgres:
    driver: local
