version: '3.5'

services:
  db:
    image: 'library/postgres:9.5'
    environment:
      POSTGRES_PASSWORD: musicloud
      POSTGRES_USER: musicloud
  php-fpm:
    user: "$UID"
    image: pldin601/musicloud-php-fpm:latest
    depends_on:
      - db
    environment:
      DB_HOSTNAME: db
      DB_DATABASE: musicloud
      DB_USERNAME: musicloud
      DB_PASSWORD: musicloud
    volumes:
      - media:/volume/media
      - temp:/volume/temp
  nginx:
    image: pldin601/musicloud-nginx:latest
    environment:
      VIRTUAL_HOST: musicloud.homefs.biz
      LETSENCRYPT_HOST: musicloud.homefs.biz
      VIRTUAL_PORT: '8080'
    depends_on:
      - php-fpm
  migration:
    image: pldin601/musicloud-migration:latest
    restart: on-failure
    depends_on:
      - db
volumes:
  media:
    driver: local
  temp:
    driver: local
